spring:
  cache:
#    type: caffeine
    type: redis
#    caffeine:
#      spec: maximumSize=1000,expireAfterWrite=5m
    redis:
      time-to-live: 300000
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "search-term::"
    cache-names:
      - searchTerms
      - searchTermById

  # Redis configuration (if using distributed cache)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
